### ISSUE TITLE
Enabling OpenGL on Linux does not add the check mark on the OSRS login menu

### ISSUE THREAD

**Issue by Meegul** [rsbmatt/OSBuddy#382]
![image](https://user-images.githubusercontent.com/4149093/35421837-63dfed5c-0213-11e8-9756-b2d642d98c10.png)

You can see the lack of check mark here, as expected as OpenGL is disabled.

![image](https://user-images.githubusercontent.com/4149093/35421853-7dc0007c-0213-11e8-88c3-a01b027186c7.png)

Now despite OpenGL being enabled as indicated by the top menu bar (which I've confirmed to be working in-game), the check mark is still missing.

This is on Ubuntu 17.10 running Oracle Java(TM) SE Runtime Environment (build 1.8.0_161-b12).

Might be related to this: running the client via the terminal shows toggling OpenGL always results in the following error, despite the graphics successfully switching over.
```
java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.Display
	at com.InsertWittyName_oj.InsertWittyName_c(InsertWittyName_oj.java:569)
	at com.InsertWittyName_oj.InsertWittyName_d(InsertWittyName_oj.java:512)
	at com.InsertWittyName_teb.InsertWittyName_a(InsertWittyName_teb.java:6)
	at com.InsertWittyName_teb.InsertWittyName_a(InsertWittyName_teb.java:4)
	at com.rsbuddy.orion.InsertWittyName_eg.InsertWittyName_a(InsertWittyName_eg.java:4)
	at com.rsbuddy.orion.InsertWittyName_eg.call(InsertWittyName_eg.java:2)
	at com.rsbuddy.orion.InsertWittyName_bg.InsertWittyName_a(InsertWittyName_bg.java:582)
	at com.rsbuddy.orion.rsi.InsertWittyName_yc.InsertWittyName_r(InsertWittyName_yc.java:503)
	at client.am(Unknown Source)
	at bd.at(Unknown Source)
	at bd.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rsbmatt** [comment]
It sounds to me like OpenGL was not actually enabled. Do you have `xorg-xrandr` installed?

You can test it by running `xrandr --version` in terminal

**Comment by Meegul** [comment]
Yep, I've got xorg-xrandr. I also can confirm that OpenGL is actually working, which... doesn't seem to make sense given the error I was getting. It does launch with OpenGL enabled and does not give that error, but attempting to disable then re-enable it throws the error.
