### ISSUE TITLE
Jagex World Map

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#40]
Maximized window with fullscreen option. Could feel map start to lag as it ran out of memory doing a lot of zooming.

> OSBuddy version: 3.0.10.6
> Operating system: Mac OS X
> Architecture: x86_64
> Java version: 1.8.0_20-ea
> Total CPU threads: 2
> Max memory: 477626368
> Free memory: 160717976
> Total memory: 347602944

`Exception in thread "Thread-17" java.lang.OutOfMemoryError: Java heap space
	at jj.<init>(Unknown Source)
	at ak.p(Unknown Source)
	at ak.m(Unknown Source)
	at ae.i(Unknown Source)
	at kw.q(Unknown Source)
	at bx.hy(Unknown Source)
	at bx.hy(Unknown Source)
	at bx.hy(Unknown Source)
	at bx.hy(Unknown Source)
	at ev.hc(Unknown Source)
	at bx.hy(Unknown Source)
	at bx.hy(Unknown Source)
	at ev.hc(Unknown Source)
	at client.fn(Unknown Source)
	at client.av(Unknown Source)
	at bo.n(Unknown Source)
	at bo.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by rsbfox** [comment]
Bug is in official client too.

**Comment by ShivamMistry** [comment]
I have provided a possible fix for this that is ready to be merged for the next update.

**Comment by rsbfox** [comment]
https://rsbuddy.com/osbuddy/patch_notes/3.0.18
