### ISSUE TITLE
Kruk's Dungeon using a lot of memory

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#75]
> Exception in thread "Thread-17" java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:359)
	at com.rsbuddy.orion.rsi.wrapper.Canvas.resetBuffers(Canvas.java:4)
	at com.rsbuddy.orion.rsi.wrapper.Canvas.getGraphics(Canvas.java:140)
	at bl.o(Unknown Source)
	at client.av(Unknown Source)
	at bo.n(Unknown Source)
	at bo.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

Reported by multiple people. Has existed since release of mm2. Might be Jagex bug.
v3.0.13

**Comment by rsbfox** [comment]
Note to self: message Fenlel#7394 on discord on any updates to this.

**Comment by rsbfox** [comment]
Memory usage issue in official client as well.

![image](https://user-images.githubusercontent.com/30416150/29043270-741a3ec8-7b88-11e7-87ef-62bdad3668f6.png)

**Comment by rsbfox** [comment]
https://rsbuddy.com/osbuddy/patch_notes/3.0.18
