### ISSUE TITLE
org.lwjgl.LWJGLException: Pixel format not accelerated

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#83]
Posting for CptLegshot (KenBlock)#9239
-

> ERROR com.InsertWittyName_ij OpenGL - Creating the display
> ERROR com.InsertWittyName_leb OpenGL - 
> org.lwjgl.LWJGLException: Pixel format not accelerated
> 	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[osbuddy/:na]
> 	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[osbuddy/:na]
> 	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[osbuddy/:na]
> 	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[osbuddy/:na]
> 	at org.lwjgl.opengl.Display.create(Display.java:848) ~[osbuddy/:na]
> 	at org.lwjgl.opengl.Display.create(Display.java:797) ~[osbuddy/:na]
> 	at com.InsertWittyName_ij.InsertWittyName_e(InsertWittyName_ij.java:209) ~[osbuddy/:na]
> 	at com.InsertWittyName_ij.InsertWittyName_d(InsertWittyName_ij.java:182) ~[osbuddy/:na]
> 	at com.InsertWittyName_leb.InsertWittyName_a(InsertWittyName_leb.java:7) [osbuddy/:na]
> 	at com.InsertWittyName_leb.InsertWittyName_a(InsertWittyName_leb.java:6) [osbuddy/:na]
> 	at com.rsbuddy.orion.InsertWittyName_dg.InsertWittyName_a(InsertWittyName_dg.java:4) [osbuddy/:na]
> 	at com.rsbuddy.orion.InsertWittyName_dg.call(InsertWittyName_dg.java:3) [osbuddy/:na]
> 	at com.rsbuddy.orion.InsertWittyName_ag.InsertWittyName_a(InsertWittyName_ag.java:176) [osbuddy/:na]
> 	at com.rsbuddy.orion.rsi.InsertWittyName_vc.InsertWittyName_n(InsertWittyName_vc.java:38) [osbuddy/:na]
> 	at client.ag(Unknown Source) [na:na]
> 	at bo.j(Unknown Source) [na:na]
> 	at bo.run(Unknown Source) [na:na]
> 	at java.lang.Thread.run(Unknown Source) [na:1.8.0_141]

Full system specs. [speccy.txt](https://github.com/rsbmatt/OSBuddy/files/1184971/speccy.txt)
Gpu supports OpenGL 3.1 and it's up to date.
v3.0.13

**Comment by rsbfox** [comment]
A fix was found that worked for him. https://github.com/LWJGL/lwjgl/issues/119#issuecomment-262090230
Leaving issue open incase this is something you can fix. Else close this and we will know workaround.

**Comment by rsbfox** [comment]
Osbuddy downloads Java. Should be able to patch manifest in exe that is distributed to users to fix this. https://github.com/LWJGL/lwjgl/issues/119#issuecomment-173983180
